[project]
name = "lib_infisical"
version = "0.1.0"
dependencies = [
    "infisicalsdk",
    "pydantic-settings",
]

[dependency-groups]
dev = [
    "ruff",
    "black",
    "mypy",
    "pytest",
    "pytest-cov",
]

[tool.uv]
package = true
